version: '3.7'

services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    expose:
      - 1221 
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 16379
    expose:
      - 16379
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: auth_app
    command: bash -c "alembic upgrade head && cd auth && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 1777:8000
    depends_on:
      - db
      - redis
    volumes:
      - .:/auth_app
    

volumes:
  redis-data:
  postgres_data: