"""Added server default

Revision ID: 9d1d79b3e13e
Revises: fa612cb84930
Create Date: 2023-08-12 22:43:02.215555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1d79b3e13e'
down_revision: Union[str, None] = 'fa612cb84930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'disabled',server_default='true')
    op.alter_column('user', 'is_superuser',server_default='false')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'disabled',server_default=None)
    op.alter_column('user', 'is_superuser',server_default=None)
    # ### end Alembic commands ###
